# Site settings
title: Matthias Lischka - Passionate Software Developer
description: 'S&nbsp;O&nbsp;F&nbsp;T&nbsp;W&nbsp;A&nbsp;R&nbsp;E&nbsp;&nbsp; D&nbsp;E&nbsp;V&nbsp;E&nbsp;L&nbsp;O&nbsp;P&nbsp;M&nbsp;E&nbsp;N&nbsp;T'
url: 'https://matthiaslischka.at'
baseurl: ''

google_analytics:
disqus_shortname: 

remote_theme: matthiaslischka/jekyll-uno

author:
  name: 'Matthias Lischka'
  email: mail@matthiaslischka.at
  #twitter_username: matthiaslischka
  #facebook_username: joshgerdes
  github_username:  matthiaslischka
  #linkedin_username:  matthiaslischka
  
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']
